pipeline:

  build-docker-image:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t hocs-test-viewer .
    when:
      branch: master
      event: push

  install-docker-image:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+hocs" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag hocs-test-viewer quay.io/ukhomeofficedigital/hocs-test-viewer:build-$${DRONE_BUILD_NUMBER}
      - docker tag hocs-test-viewer quay.io/ukhomeofficedigital/hocs-test-viewer:latest
      - docker push quay.io/ukhomeofficedigital/hocs-test-viewer:build-$${DRONE_BUILD_NUMBER}
      - docker push quay.io/ukhomeofficedigital/hocs-test-viewer:latest
    when:
      branch: master
      event: push

  deploy-to-dev-from-build-number:
    image: quay.io/ukhomeofficedigital/kd:v0.8.0
    environment:
      - KUBE_NAMESPACE=cs-dev
      - ENVIRONMENT=dev
      - VERSION=build-${DRONE_BUILD_NUMBER}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - hocs_test_viewer_dev
    commands:
      - cd kube
      - ./deploy.sh
    when:
      branch: master
      event: [push, tag]

  deployment:
    image: quay.io/ukhomeofficedigital/kd:v0.8.0
    environment:
      - KUBE_NAMESPACE=cs-${DRONE_DEPLOY_TO}
      - ENVIRONMENT=${DRONE_DEPLOY_TO}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - hocs_test_viewer_dev
    commands:
      - cd kube
      - ./deploy.sh
    when:
      event: deployment
      environment: [dev, qa]
