---
apiVersion: extensions/v1
kind: Deployment
metadata:
  annotations:
    downscaler/uptime: Mon-Fri 08:00-17:30 Europe/London
  name: hocs-test-viewer
  labels:
    version: {{.VERSION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hocs-test-viewer
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: hocs-test-viewer
        role: hocs-backend
        version: {{.VERSION}}
    spec:
      imagePullSecrets:
        - name: registrykey
      containers:
        - name: certs
          image: quay.digital.homeoffice.gov.uk/ukhomeofficedigital/cfssl-sidekick:v0.0.6
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          args:
            - --certs=/certs
            - --domain=hocs-test-viewer.${KUBE_NAMESPACE}.svc.cluster.local
            - --expiry=8760h
            - --command=/usr/local/scripts/trigger_nginx_reload.sh
          env:
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: certs
              mountPath: /certs
            - name: bundle
              mountPath: /etc/ssl/certs
              readOnly: true

        - name: proxy
          image: quay.digital.homeoffice.gov.uk/ukhomeofficedigital/nginx-proxy:v3.4.2
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          resources:
            limits:
              memory: 512Mi
              cpu: 250m
            requests:
              memory: 256Mi
              cpu: 150m
          env:
            - name: PROXY_SERVICE_HOST
              value: '127.0.0.1'
            - name: PROXY_SERVICE_PORT
              value: '3000'
            - name: NAXSI_USE_DEFAULT_RULES
              value: 'FALSE'
            - name: ENABLE_UUID_PARAM
              value: 'FALSE'
            - name: HTTPS_REDIRECT
              value: 'FALSE'
            - name: SERVER_CERT
              value: /certs/tls.pem
            - name: SERVER_KEY
              value: /certs/tls-key.pem
            - name: ADD_NGINX_HTTP_CFG
              value: |
                proxy_read_timeout 10s;
            - name: ADD_NGINX_SERVER_CFG
              value: 'location = /reload { allow 127.0.0.1; deny all; content_by_lua_block { os.execute("touch /tmp/nginx-reload-triggered; /usr/local/openresty/nginx/sbin/nginx -s reload; touch /tmp/nginx-reload-complete;") } }'
          volumeMounts:
            - name: certs
              mountPath: /certs
              readOnly: true
            - name: secrets
              mountPath: /etc/nginx/secrets
              readOnly: true
          ports:
            - name: https
              containerPort: 10443
        - name: hocs-test-viewer
          image: quay.digital.homeoffice.gov.uk/ukhomeofficedigital/hocs-test-viewer:{{.VERSION}}
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          env:
          - name: HTTP_PROXY
            value: http://hocs-outbound-proxy.{{.KUBE_NAMESPACE}}.svc.cluster.local:31290
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: cs-integration-testing-s3
                key: access_key_id
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: cs-integration-testing-s3
                key: secret_access_key
          - name: DASHBOARD_BUCKET
            valueFrom:
              secretKeyRef:
                name: cs-integration-testing-s3
                key: name
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 150m
              memory: 128Mi
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              httpHeaders:
                - name: X-probe
                  value: kubelet
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
              httpHeaders:
                - name: X-probe
                  value: kubelet
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 10
      volumes:
        - name: certs
          emptyDir:
            medium: "Memory"
        - name: bundle
          configMap:
            name: bundle
        - name: secrets
          emptyDir:
            medium: "Memory"
