---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/enabled: "true"
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/ingress.class: nginx-internal
  labels:
    cert-manager.io/solver: route53
  name: hocs-test-viewer-internal
spec:
  rules:
  - host: {{.DOMAIN_NAME}}
    http:
      paths:
      - backend:
          serviceName: hocs-test-viewer
          servicePort: 443
        path: /
  tls:
  - hosts:
    - {{.DOMAIN_NAME}}
    secretName: hocs-test-viewer-internal-tls
