---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/enabled: "true"
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/ingress.class: nginx-external
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: test-viewer-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - HOCS"
  labels:
    cert-manager.io/solver: http01
  name: hocs-test-viewer
spec:
  rules:
  - host: {{.DOMAIN_NAME}}
    http:
      paths:
      - backend:
          serviceName: hocs-test-viewer
          servicePort: 443
        path: /   
  tls:
  - hosts:
    - {{.DOMAIN_NAME}}
    secretName: hocs-test-viewer-external-tls
